### PR TITLE
added functions mc/split-region[-regexp]

### PR DESCRIPTION
**Pull request by nispio**
This commit adds the `mc/split-region` and `mc/split-region-regexp` commands as requested and discussed in #292

### CODE REVIEW

**Comment by magnars** [comment]
Thanks for this. Any chance you could add an example for each to the tests? You'll find them under the `features` folder.

**Comment by nispio** [comment]
There seems to be a specific grammar to that file.  Is it machine readable? If so, where can I learn more about the language in use?

**Comment by nispio** [comment]
I thought I had it figured out.  My tests pass on the locally when I run `./run-tests.sh`  Any tips on debugging differences between local ecukes results and the ones on the Travis CI server?

**Comment by nispio** [comment]
Okay, I'm stumped.  I wrote tests that work for me on my local install.  I tried running them locally against emacs-24.3 which Travis CI seems to be using, and they still pass.  Any thoughts on why these tests would fail in Travis but pass locally?  I am particularly stumped about the extra scenario I added called "Separate kills."  It should only be relying on fairly basic Multiple Cursors behavior.  What am I missing?

**Pull request closed without merging**
