### PR TITLE
Fix Backspace for Smartparens

### PR DESCRIPTION
**Pull request by szw**
Hi! 

Thanks for a great plugin! I found that Backspace does not work well when Smartparens Mode is on. 
Here's an addition to default commands allowed to run for all cursors.

All the best,

szw

### CODE REVIEW

**Comment by gittan** [comment]
Same goes for hungry-delete-backward and hungry-delete-forward

**Comment by magnars** [comment]
I'm not convinced that multiple-cursors should include defaults for packages outside of emacs core. Just answer "yes" when asked if the command should be done for all cursors.

**Comment by Compro-Prasad** [comment]
@szw @magnars Why isn't this closed?

**Comment by magnars** [comment]
I didn't close it because I was open for arguments. Seems noone was interested in arguing the case, so yeah, time to close I guess.

**Pull request closed without merging**
