### PR TITLE
mark-previous-like-this-word/symbol.

### PR DESCRIPTION
**Pull request by AndreaOrru**
Added these two missing functions (like mark-next-like-this-word but going backwards).

### CODE REVIEW

**Comment by magnars** [comment]
Makes sense. Thanks. Would you mind adding some tests?

**Comment by AndreaOrru** [comment]
There you go :)

**Comment by AndreaOrru** [comment]
Woah, it fails on Emacs 24 but it passes on Emacs 25.
I'll investigate.

**Comment by AndreaOrru** [comment]
There you go. Solved!

**Comment by magnars** [comment]
Looking good. Thanks!

**Pull request merged**
