### PR TITLE
Evil ways

### PR DESCRIPTION
**Pull request by jacobono**
This is another PR that follows from #216.

I decided to go from scratch because I knew nothing about what was really going on and needed to go through it step by step.  Also I happen to like PR's that can be named after songs ([Santana!).](https://www.youtube.com/watch?v=_tKIPuLfeKg)

I cherry picked commits where I could, but I wanted to give a shout out to @myrjola, @PythonNut, @lionel-, and @linktohack for all their work and diffs which I scoured to get an understanding of what was going on.  Without their work I would have been really lost.

Big thanks to @gabesoft, who developed [evil-mc](https://github.com/gabesoft/evil-mc), from where I shamelessly ~stole~copied tests for evil to ensure proper testing, and if not for that I would have taken a long time to test properly.

The things I wanted to do for this PR i **think** have been accomplished:

- [x] Bring in tests from `evil-mc`
- [x] documentation
- [x] get something working and tests passing (obviously)

The changes are many, so I wrote some documentation in `docs` not sure if you want to keep it @magnars, but it will help to understand some of the changes to get `evil` integrated.

Other changes to note in testing mostly:

- not allowing `mc/list-file` to be loading a users list file for testing (messed me up once before I figured out what was going on.
	- This includes a new file `mc-vars` to accomplish this.  I only included what went in the changes for this PR, but it might make sense to throw all the other variables in that file in another PR.
- Throwing an error in testing if the command isn't supported (only when using evil tests) to signal an addition needs to be made to either commands to run once/for all variables.

I most likely missed something in the documentation, or in the code cleanup -- let me know what I missed and I can fix it.

Same with questions.

Also I know it is a lot of commits, but plan to squash after convo about this.

I have used this a bit, but maybe someone else can give it a whirl.  There are bound to be some things that don't work right.

Things that aren't working that I've noticed:

- key chord doesn't work still, idk why i.e `"fn"` doesn't escape, but pressing escape does the job for now.  I would like to get it working with that keychord though.

Thanks for multiple cursors!

### CODE REVIEW

**Comment by myrjola** [comment]
Awesome work! I will test your code today. I'm very glad you have so many tests working, because that was where I got stuck.

**Comment by jacobono** [comment]
I just noticed the CI was failing -- I changed the travis yml file to test it out and it is what I suspected -- the tests hang on any version less than 25.

Not sure if that means this is a deal breaker or not.

I made the fix for `evil-escape` by wrapping some advice around it for now, but I opened [a PR](https://github.com/syl20bnr/evil-escape/pull/76) that would do the same thing in that library if it can get merged then we can change that advice.

I also got `edit-lines` to work for a `visual` selection and `visual line` selection.

Here is a cut off gif doing something really simple for a `fish` plugin -- but shows off the integration with evil pretty nicely.


[The full length version is only ~20 seconds longer](http://recordit.co/Xaoj7Px11n)

**Comment by dvzubarev** [comment]
Thanks for all your work! I tested it a bit and it works fine for all evil operators.
I encountered a couple of bugs though. Should I post them here or maybe you open an issue tracker in your fork?

**Comment by jacobono** [comment]
Thanks for testing this out! 

You can put the problems you found here.

A scenario I can copy and paste in to a test would be amazing -- at the very least I just need what key sequence you tried, what you tried it on, what you expected, and what you actually got.

**Comment by dvzubarev** [comment]
I created a couple of scenarios. Please, [see](https://gist.github.com/dvzubarev/1508bddf6146ba148d24d99fc8ff9571)

**Comment by jacobono** [comment]
thanks for the scenarios -- all was pretty easy to fix except for the undo test.

I don't have a clue what is going on there.  I created a [separate branch](https://github.com/jacobono/multiple-cursors.el/tree/evil-ways-evil-undo) to hold that test and maybe something will dawn on me why it isn't working later on.

**Comment by jacobono** [comment]
The undo case you had should be working now -- give it a go when you can!

I only found problems with it when only two cursors were present.  Any cursor count `> 2` works as is.  With only two cursors the `buffer-undo-list` looks like

`(nil (apply activate-cursor-for-undo 51) nil (8 . 9) 7 nil (apply deactivate-cursor-after-undo 51) nil (2 . 3) 1 nil undo-tree-canary)`

*I got this from running manually through the scenario you provided in the scratch buffer*

`activate-cursor-for-undo` pops the cursor (restores state and removes the cursor).  Undo is only called for the main cursor, so when going through the `post-command-hook` it sees the `1` count for cursors and disables `multiple-cursors-mode`.  Which is what you were seeing.  Checking for a cursor undo being active when the number of cursors is 1 alleviates this.

Only problem is the tests don't work no matter what.  The output of `buffer-undo-list` when running the scenario you provided me is

`((apply activate-cursor-for-undo 5) nil (8 . 9) 1 (apply deactivate-cursor-after-undo 5) nil (2 . 3) 1 nil undo-tree-canary)`

For whatever reason they aren't the same shape.  I expect the `5` and `51` discrepancy, but the other two glaring problems are

> manual scratch buffer

`(8 . 9) 7 nil`

> when running test

`( 8 . 9) 1 (apply deactivate ..`

the `nil` is an undo boundary, that is why for two cursors in this scenario you hit undo **4** times.  In the test though, it is missing the `nil` so you only do `press "uuu"`.

The other thing is the `7` versus the `1` after `(8 . 9)` pair.  This undo element moves point to the position.  For whatever reason in the test, `evil-paste-after` puts `1` but when *actually* doing the paste operation it puts in the `7`.

This completely throws the tests off.  And I have no clue how to fix it.  Just leaving this here in case someone has an idea why this doesn't work with `ecukes`.

**Comment by dvzubarev** [comment]
Thank you for fixing the problems. I use this branch daily now.  I've created another scenarios, please  [see](https://gist.github.com/dvzubarev/76424ebd41e5b3646512b064a97e2dc8).

**Comment by jacobono** [comment]
the only scenario that doesn't work is the undo one you provided.

That isn't a fault of the code as far as I can tell.  The undo command moves the main cursors point back to 2 which would be

```
t|est
test
```

but in between that there is an `activate-cursor-for-undo` and a `deactivate-cursor-for-undo`.

The former is called first, and then the "te" is restored, with the point and mark being at (4,4).

the latter is called and the fake cursor is created again at (4,5) which is fine actually and the the undo for the main cursor happens adjusting those markers to (6,7) ("adding the `te` characters").  leaving you with these cursor positions

```
t|est
|test
``` 

This is rather complicated as everything is actually working the way it supposed to (I think).

Anyway, since I couldn't figure it out I put the scenario in the same undo branch I mentioned in an earlier post.

**Comment by jojojames** [comment]
@jacobono Is there anything stopping this branch from getting merged? I see last update was July 21st. :)

**Comment by deb0ch** [comment]
Hi, I want to start playing around with multiple-cursors in evil, does this PR supersede #216 ?

**Pull request closed without merging**
