### PR TITLE
Make "no more matches found." user-error, fix #218

### LINKED ISSUE #218: "no more matches found." should be a user-error
Currently it's an error, which triggers a backtrace whenever I happen to have `debug-on-error` enabled. I think `user-error` would be more appropriate for this situation.

### PR DESCRIPTION
**Pull request by drrlvn**

### CODE REVIEW

**Comment by Fuco1** [comment]
Yes please, I was just about to make a PR myself but then decided to check first.  The current UX is very annoying.

**Comment by Fuco1** [comment]
@drrlvn Do you think it would make sense to also change the other errors to user errors? Like `"No cursors to be skipped"` or `"No cursors to be unmarked"`. I think it would make sense.

**Comment by magnars** [comment]
Thanks! This makes sense. You're both added as Collaborators is. Feel free to push more common sense fixes like this. :+1:

**Comment by Fuco1** [comment]
@magnars you're getting lazy my friend! :D Thanks!

**Comment by drrlvn** [comment]
With great power comes great responsibility! Or something like that... ;)
Thanks!

**Pull request merged**
