### PR TITLE
(WIP) Evil compatibility

### PR DESCRIPTION
**Pull request by myrjola**
Starting to work on issues syl20bnr/spacemacs/issues/2669, #17 and #158. Some progress has been made, but this is far from finished.

Fixed so far:
- Cursor movement when switching between insert and normal state
- Simple operator-motion-combinations, like `de` i.e. "delete to end of word".

For now I'm not worrying that much about code elegance. Just wrapping my head around what is broken and trying to fix it one step at a time. However, all kinds of pointers regarding the code are much appreciated.

### CODE REVIEW

**Comment by myrjola** [comment]
The problem fixed in d1e7a0a is documented more thoroughly in https://github.com/syl20bnr/spacemacs/issues/2669#issuecomment-136178913 and https://github.com/syl20bnr/spacemacs/issues/2669#issuecomment-137578889. It can be demonstrated with the following org-mode snippet:

```
#+BEGIN_SRC emacs-lisp
(defun reproduce-bug (keys)
  (interactive (list (this-command-keys)))
  (message "Keys pressed: %s" keys))
#+END_SRC

#+RESULTS:
: reproduce-bug

#+BEGIN_SRC emacs-lisp
(progn
  (call-interactively 'reproduce-bug)
  (call-interactively 'reproduce-bug))
#+END_SRC

#+RESULTS:
: Keys pressed: ^C^C

This simulates what's happening in a fake cursor:

#+BEGIN_SRC emacs-lisp
(progn
  (call-interactively 'reproduce-bug)
  (run-hooks 'post-command-hook)
  (call-interactively 'reproduce-bug))
#+END_SRC

#+RESULTS:
: Keys pressed: 
```
The post-command-hook called by `mc/execute-command` resets the `this-command-keys` related state and so the second `reproduce-bug`-call doesn't return any keys pressed.

**Comment by Devagamster** [comment]
Make sure to add 'temporary-goal-column to the cursor specific vars.

**Comment by myrjola** [comment]
@Devagamster, I added it in 96e9c11. What does it fix?

**Comment by Devagamster** [comment]
Pasted from previous thread:

If you have multiple cursors but have them staggered across different columns, repeatedly moving up or down a column will cause all of the cursors to jump to the same column instead of preserving their current horizontal position.

Fix: Add temporary-goal-column to mc/cursor-specific-vars with (push 'temporary-goal-column mc/cursor-specific-vars)

**Comment by myrjola** [comment]
The Evil compatibility is nearly usable for me now as the biggest problems have gotten fixed. There's still many cases that break and the code isn't in a mergeable state. Maybe at this point I should start thinking about implementing tests for all the broken cases I run into before moving forward with fixing them. 

It would also be great if someone had the time to test and/or review the code so far :wink:

**Comment by Devagamster** [comment]
I have looked at the code you have so far and it looks pretty good. My only concern is regarding advice to a native function. I don't remember the details at all, but i seem to recall reading somewhere that advising a native c function can have weird results. Could be a non issue...
I definitely think writing tests for this would make the process of fixing it much more maintainable. I don't have the elisp chops to set up a test framework, but if you were to give a couple of examples, I could write tests for issues I find as well.
Currently the the biggest problem after these fixes I encounter is with visual mode. I am sure there are many other problems with registers as well, I just haven't gotten around to taking a look at them.

Looks real close!

Sent from my Windows Phone
________________________________

**Comment by PythonNut** [comment]
@myrjola I just took this for a test drive. It already seems to be working for all the operator+motions I commonly use, with the exception of the `evil-find-char(-backward)?(-to)?` motions.

I'll post if I can find anything else broken. I'm sorry but I'm not much of an Elisp expert, and I have no idea how to write tests for interactive stuff. I might manage to learn, but at least for now I can only provide minimal breaking examples.

**Comment by myrjola** [comment]
Thanks @Devagamster for the heads up regarding advising a native C-function. I'll try to find some references regarding that. Recall from https://github.com/magnars/multiple-cursors.el/pull/216#issuecomment-137857147 that something in the post-command-hook resets what's returned by `this-command-keys`. Fixing the problem from there could also work.

Thanks @PythonNut for reporting the problem with the `evil-find-char(-backward)?(-to)?`. I'll put that on my list.

**Comment by myrjola** [comment]
I also noticed that `evil-repeat` is broken. Putting that on my list.

**Comment by Devagamster** [comment]
Another interesting bug to add to the list is that if you use visual line mode and call mc/edit-lines, if you move the point up it works fine, but moving down from the start position and calling mc/edit-lines causes one too many cursors to be created.

**Comment by Devagamster** [comment]
Another bit to consider, is that having a good set of evil defaults for the `mc/cmds-to-run-for-all` and `mc/cmds-to-run-once` variables would be a very good idea. The ones I have thus far (unfortunately including some spacemacs-isms):

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        evil-append
        evil-append-line
        evil-backward-char
        evil-backward-paragraph
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-downcase
        evil-end-of-line
        evil-escape-insert-state
        evil-first-non-blank
        evil-force-normal-state
        evil-forward-char
        evil-forward-paragraph
        evil-forward-word-begin
        evil-forward-word-end
        evil-goto-line
        evil-insert
        evil-jump-item
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-search-next
        evil-snipe-f
        evil-visual-char
        evil-visual-line
        evil-yank))

This is by no means comprehensive, but a useful baseline.

**Comment by myrjola** [comment]
Thank you @Devagamster! I added the baseline. I didn't have any additional commands in my .mc-lists.el. But will try to add more commands to that variable as they appear. My progress has slowed somewhat as school has started, but I intend to squeeze in some multiple-cursors love during weekends.

**Comment by Devagamster** [comment]
@myrjola are you still planning on getting tests setup for this? Like I said earlier, I don't think I understand emacs/elisp enough to set it up on my own, but if you were to get a framework up I would love to find and write tests for lots of evil inconsistencies. Then would start to build a list of things that need fixed.

**Comment by myrjola** [comment]
@Devagamster, yeah. The tests are next on my list. I'll build them as part of the suite that is already present in this project. I havent taken a closer look on that though, but I hope that the framework already present is sufficient.

**Comment by Devagamster** [comment]
@myrjola Ok I'll take a look and see what I can come up with later tonight if I get the time.

**Comment by myrjola** [comment]
I added some evil-compat tests get started. I noticed that some of the original tests break by only calling `(require 'evil)`. It seems that the tests are related to `rectangular-region` and `delete-selection-mode`. I'll try to see what can be done about this. I already tried `(unload-feature 'evil t)` to reverse the require, but that doesn't work. I tried to reproduce some of the failures in my scratch buffer, but everything worked fine when I tried all the steps there.

One simple solution would be to run the evil-compat tests last, but better to try to get to the bottom of this first.

**Comment by myrjola** [comment]
I didn't yet figure out why the build breaks after loading evil with `(require 'evil)`. I started by investigating the `delete-selection-mode` tests. I introduced a debug step:

```
(Then "debug print \\(.+\\)"
      (lambda (variable)
        (message "%s: %s" variable (eval (intern-soft variable)))))
```

So now I know that `delete-selection-mode` is active and doesn't get disabled during the test:

```
bash-3.2$ cask exec ecukes -p delete-char
Loading /Users/martin/.emacs.d/.mc-lists.el (source)...
Delete-Selection mode enabled
Delete-Selection mode enabled
Delete-Selection mode enabled
delete-selection-mode: t
Mark set
Mark set
delete-selection-mode: t
delete-selection-mode: t
delete-selection-mode: t
delete-selection-mode: t
.

  Scenario: delete-selection-mode (delete-char)
    Given I turn on delete-selection-mode
    Then debug print delete-selection-mode
    And I have cursors at "text" in "This text contains the word text twice"
    Then debug print delete-selection-mode
    And I press "C-SPC"
    Then debug print delete-selection-mode
    And I press "M-f"
    Then debug print delete-selection-mode
    And I press "C-d"
    Then debug print delete-selection-mode
    Then I should see "This  contains the word  twice"
      Expected
      This  contains the word  twice
      to be part of:
      This textcontains the word texttwice

1 scenarios (1 failed, 0 passed)
18 steps (1 failed, 0 skipped, 17 passed)
```

I'll have to sleep on this. If anyone has an idea what is happening or has suggestions moving forward, please chime in.

**Comment by mtszsobczak** [comment]
@myrjola 
Hi, I really look forward to see multiple-cursors combined with evil mode :). Keep up good work :+1: !!

**Comment by myrjola** [comment]
@mtszsobczak  Thanks for the encouragement! I'm sad to say I can't allocate that much time to this anymore. Last weekend I tried to debug the issue in https://github.com/magnars/multiple-cursors.el/pull/216#issuecomment-139891207 further, but to no avail.

I think it's best that I strive to get the current compatibility changes to a mergeable state. Some refactoring needs to be done and I have to get the tests working again. After we get the initial support merged I will create issues about the other evil-features that do not yet work in multiple-cursors. What do you @magnars think about this?

Alternatively we could create an evil-compat branch to magnars/multiple-cursors.el where evil related pull requests could be made by others and that branch would then be merged to master at the appropriate time.

**Comment by magnars** [comment]
@myrjola Thanks for your work on this! I'm sorry I haven't been able to be of more help.

> I think it's best that I strive to get the current compatibility changes to a mergeable state. Some refactoring needs to be done and I have to get the tests working again. After we get the initial support merged I will create issues about the other evil-features that do not yet work in multiple-cursors. What do you @magnars think about this?

What sort of state is the evil support in at the moment? Is it usable most of the time, apart from some edge cases? Or is it a minefield of commands that doesn't work?

**Comment by myrjola** [comment]
@magnars I think the functionality is in usable state. Most importantly state transitions, operator motions and visual state works. There are edge cases, especially in the visual state compatibility. But for simple editing the current state is sufficient.

**Comment by magnars** [comment]
In that case, I'm in favor of rolling these changes in now (with tests),
and open issues for the remaining things.
ons. 23. sep. 2015 kl. 18.20 skrev Martin Yrjölä <notifications@github.com>:

**Comment by myrjola** [comment]
Excellent! I'll strive to get this done in a couple of weeks.

**Comment by noprompt** [comment]
I'd be happy with this even if visual state wasn't supported right away. This is one of those libraries I've been wanting to use but incompatibility with evil mode has put it on hold.

**Comment by xificurC** [comment]
Looking forward to this addition as well, much appreciated!

**Comment by snario** [comment]
There is no way to use the mouse to select an area, then select a second area, am I correct here? I have been playing around with this PR

**Comment by gabesoft** [comment]
Hey guys, I've been working on a multiple cursors implementation as well. It's still a work in progress but it's usable. Check it out here https://github.com/gabesoft/evil-mc

**Comment by PythonNut** [comment]
@gabesoft is `evil-mc` a completely new package, or does it leverage `multiple-cursors`? It's kinda unfortunate that we have duplicated effort here.

**Comment by gabesoft** [comment]
@pythonut it's new and it's more of an experiment. If it does end up being useful I'm sure we can find a way to merge it into multiple-cursors.

**Comment by torgeir** [comment]
> @magnars I think the functionality is in usable state. Most importantly state transitions, operator motions and visual state works.

That's awesome! Been using this along with evil for some time now, limiting myself to just doing `c` in combination with multiple cursors and expand region. It's actually been working out pretty good, but I've been longing for the other operator motions - I can't wait to see this one merged! Gj

**Comment by myrjola** [comment]
I have to apologise for not giving any updates in a long time. I have a brutal schedule until the end of the year, so I won't have time to finish my work on the evil support until then. I'm sorry for disappointing you all.

I have to admit I'm using `evil-mc` in the meantime. But I still think that it would be better to only have one general multiple cursors package.

So what is needed to get the current functionality into working state is:
1. Figure out why `(require 'evil)´ breaks some tests. See https://github.com/magnars/multiple-cursors.el/pull/216#issuecomment-139891207.
2. Write more tests to ensure that the basic support works.
3. Ensure that all tests pass.

If anyone wants to give it a shot I will gladly give write permissions to https://github.com/myrjola/multiple-cursors.el. That way we can continue the discussion in this PR.

**Comment by PythonNut** [comment]
@myrjola I'll give it a shot. I can't promise anything: it sounds like my schedule pretty similar to yours, and I'm probably out-of-my-depth for at least a few things that need to be done.

But this is something that I think is awesome, and I'm willing to try to be useful.

**Comment by myrjola** [comment]
@PythonNut, many thanks and good luck! I have added you as a collaborator to myrjola/multiple-cursors.el. Your pushes to the evil-compat branch should be seen in this pull request.

**Comment by idoo** [comment]
just subscribe

**Comment by rebcabin** [comment]
As of 2015 Nov 21, mc/edit-lines not working in spacemacs develop branch.  Here is my .spacemacs http://pastebin.com/5Ez75Zav in case you have time to have a look.

I have an opportunity to "sell" spacemacs to an influential VIM user... the guy does a LOT of column-oriented editing and I am sure that a working mc/edit-lines would be very persuasive. Failing that, I will show him `C-X r k` the rectangular commands and the table editor in org-mode, but mc is so much more :)

**Comment by magnars** [comment]
Didn't Spacemacs switch to evil-mc?
søn. 22. nov. 2015 kl. 05.31 skrev rebcabin <notifications@github.com>:

**Comment by rebcabin** [comment]
Let me check -- for sure mc/ does not work in emacs mode (i'll see if evil-mc can work in emacs mode -- i don't use the vim mode)

**Comment by syl20bnr** [comment]
There is no official switch yet, in develop branch one can test `evil-mc` by adding `(require 'evil-mc)` in their `user-config` function.
This is weird that MC does not work in emacs state, I believed that some Evil users successfully used it like this (or maybe they switch to insert state). Another possibility is to completely disable evil when entering MC and reenable it when leaving.

**Comment by PythonNut** [comment]
`multiple-cursors` works fine for me in both `insert` and `emacs` states (custom config).

**Comment by sooheon** [comment]
@myrjola how should we help testing these features? Currently should I just look at the diffs in your PR, apply the locally? I don't see an `evil-compat` repo in your profile which I can clone.

Anyway having manually copied your changes, I'm finding the biggest problems are fixed for me, specifically the cursor movement after insert. 

Two strange things I noticed: Undoing after a backwards delete (`db`, for example) moved the main cursor back to the correct place, but all secondary cursors remained in the position after deletion, only restoring text. The same operation with `backward-kill-word` from insert-state restored cursors to correct place after undo. The other is that visual deletions leave mc in a strange state. To reproduce, with mc, visually select a word or two, then `d` or `x`. Then, pressing `v` again will only put one or two of the cursors into visual mode again. Pressing esc in this weird state sometimes leaves a ghost cursor which cannot be removed with `C-g`. 

Still, thanks for all your hard work, and don't feel too pressured--it's very daunting to integrate two such intricate tools, and we all should thank you for the effort, regardless of how long it takes.

**Comment by myrjola** [comment]
Thanks for the kind words @sooheon!

First of all you can find my work [here](https://github.com/myrjola/multiple-cursors.el/tree/evil-compat). I rebased on the latest upstream changes. Good to hear that the biggest problems were fixed for you, that was my impression as well. I didn't just have time to get the tests working, so that the basic support could be merged. I'm afraid I'm still too busy to give it another shot for the coming months, but I have high hopes for summer. The current status is summarized in https://github.com/magnars/multiple-cursors.el/pull/216#issuecomment-155408556 and I'm happy to give push access to my fork if someone wants to continue the work.

Thank you for reporting the issues as well. Now there's more edge cases documented.

**Comment by lionel-** [comment]
hi @myrjola 

Could you grant me access to your branch? I have a couple more fixes ready. See https://github.com/lionel-/multiple-cursors.el/tree/evil

**Comment by myrjola** [comment]
Hi @lionel-! I added you. Thank you for pushing this forward.

There's also some interesting work on implementing multiple cursors in Emacs core https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-03/msg00051.html. Maybe that will make it possible to support Evil more cleanly.

**Comment by lionel-** [comment]
Thanks!

Just pushed a few commits that should make things more usable. In particular pasting is now improved. Still a lot of quirks though. I think we'll eventually need to reproduce evil states more fully. I don't have time to work on this a lot unfortunately.

> Maybe that will make it possible to support Evil more cleanly.

Indeed, support for cursor-local variables should make things a lot easier.

**Comment by rvion** [comment]
any update? :)

**Comment by lionel-** [comment]
It's already usable, there are bugs here and there, but I don't think I'll ever be bothered enough to fix them all as I have other things to do. I use this branch all the time though, so definitely usable.

**Comment by sooheon** [comment]
Can confirm, I'm also using this daily and it's 90% fine. I think I've adjusted to stay away from certain iffy operations, like too much maneuvering between states and repetition of editions with `.`.

**Comment by ninrod** [comment]
How is this going gentlemans?

**Comment by NerdsvilleCEO** [comment]
What is the status on this, I would love this functionality :) right now am using evil-multiedit

**Comment by ninrod** [comment]
@NerdsvilleCEO, stalled. nobody is standing up to the challenge.

**Comment by NerdsvilleCEO** [comment]
Hm well I'm new to emacs and lisp this would probably be a good challenge for me, what's left to finish?

**Comment by ninrod** [comment]
@NerdsvilleCEO, in theory, you should manually load @linktohack 's [fork](https://github.com/linktohack/multiple-cursors.el/tree/master) because it is the most updated fork in existance of the evil-compat branch. I've used it and found many many bugs. So the task would be to bughunt all those bugs until it is decently usable.

**Comment by linktohack** [comment]
Nothing fancy (and a lot of bugs as @ninrod mentioned,) but this snippet https://gist.github.com/linktohack/30b1122f1efdafe3f7c7#file-init-el-L607 (line 607 to 636) gives me a quite close experience to Sublime Text (double click and drag to highlight other occurrences, <kbd>cmd-d</kbd>, <kbd>cmd-k</kbd><kbd>cmd-d</kbd> etc.)

**Comment by NerdsvilleCEO** [comment]
I'm out getting lunch now but I presume some bugs are already listed as issues there right?

**Comment by ninrod** [comment]
@NerdsvilleCEO not really: it's a fork and you can't add issues to a fork, apparently. 
And even if you could, we're talking uncharted territory. You could create a dedicated repo to work on this though, and after it is stable you could open the pull-request. Many ways to handle this.

**Comment by ninrod** [comment]
Hi @linktohack, simply calling `link/mark-next` makes emacs delete my entire buffer and replace with a single line: `link/mark-next`.

first

And then when I hit return:

error

**Comment by linktohack** [comment]
Sorry for the confusion, @ninrod Did you try to eval this https://github.com/linktohack/highlight-selection/blob/master/highlight-selection.el in `*scratch*` buffer. It's working fine for me https://www.dropbox.com/s/38cafbvv2e0lxho/Screenshot%202017-01-17%2020.06.07.png?dl=0

And sorry others for hijacking the thread...

**Comment by ninrod** [comment]
Yes I've git cloned your highlight selection repo and used use-package's `:load-path` to load it up correctly. 

This same behaviour happens to me even if I manually install @myrjola's or your branch. 

It really does not play well with my config. I have +2.2k of elisp configuration bordering 100 packages.

**Comment by linktohack** [comment]
Looks like `highlight-selection` does not work for you. `link/mark-next` is very simple, just remove the related line in the definition and you should be good to go (without highlighting all occurrences though)
```emacs-lisp
(defun link/mark-next ()
      (interactive)
      (unless (use-region-p)
        (mc--mark-symbol-at-point))
      ;; (call-interactively 'highlight-selection-current-selection)
      (mc/mark-next-like-this 1)
      (mc/cycle-forward))
```

**Comment by ninrod** [comment]
Hi @linktohack. This same behaviour happens if I don't use your configuraiton at all and instead install, say, myrjola's branch and try to use any `mc/* command`. 

I'm using evil-mc with success though.

**Comment by PythonNut** [comment]
https://github.com/PythonNut/multiple-cursors.el/issues is a fork with an issue tracker. If people know of bugs, we can start collecting them there.

**Comment by NerdsvilleCEO** [comment]
Sounds good to me, I'll check that out next week, been quite busy lately

**Pull request closed without merging**
