### PR TITLE
Update README.md according to mc/always-run-for-all

### PR DESCRIPTION
**Pull request by bb2020**
Provided documention for `mc/always-run-for-all`. Mentioned in #252 .

### CODE REVIEW

**Comment by bb2020** [comment]
Changed my mind about the joke.

**Comment by bb2020** [comment]
Ping @jtamagnan

**Comment by jtamagnan** [comment]
Hey sorry, I've read this over I want to edit the text a bit but I'll pull
it in when things are a bit less hecktic on my end. Thanks so much for the
help and the ping

**Comment by bb2020** [comment]
Looks like this issue has been accitentally closed while I was trying to force push
into my fork. The commit is https://github.com/bb2020/multiple-cursors.el/commit/42cc41d0a8bc3e282191df3466cd21a3f08ca12e or
I can send a new request.

**Comment by jtamagnan** [comment]
@bb2020 I updated the readme saying the same thing as you. I simply rephrased

**Pull request closed without merging**
