### PR TITLE
Use GitHub Actions in place of Travis, and test more Emacs versions

### PR DESCRIPTION
**Pull request by purcell**
The CI setup here has decayed, so I thought I'd have a quick look at overhauling it, since I've done this a few times already.

### CODE REVIEW

**Comment by purcell** [comment]
Stopping here because ecukes isn't happy, and that's a rabbit hole I'm not keen to explore. https://github.com/purcell/multiple-cursors.el/runs/1300842169?check_suite_focus=true

**Comment by magnars** [comment]
Ahh, this seems like a wonderful change. Unfortunately, there seems to be an endless series of rabbit holes in this stack. Maybe that's a bad use of the metaphor. In either case, thank you for giving it a shot. This seems like an excellent start to get the CI up and running again.

**Comment by purcell** [comment]
If it weren't for Emacs, I'd just do something like I do in a number of other repos, and skip Cask entirely: https://github.com/jcollard/elm-mode/blob/master/Makefile

**Comment by jtamagnan** [comment]
I poked around a bit and it seems like github-actions doesn't support TTYs and it seems like its not on their roadmap https://github.com/actions/runner/issues/241

I was able to poke around and get something that seemed to work: https://github.com/jtamagnan/multiple-cursors.el/runs/1558510716?check_suite_focus=true

```
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 100fa95..72f9991 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,4 +35,4 @@ jobs:
     - name: Install dependencies with Cask
       run: cask
     - name: Run tests
-      run: script -e -c /bin/bash -c 'TERM=xterm ./run-tests.sh'
+      run: ./run-tests.sh
```

**Comment by purcell** [comment]
This at least seems to run ecukes tests, one of which fails. Since travis is _more_ broken that this, I'll go ahead and merge this.

**Pull request merged**
