### PR TITLE
Add mc/eval-and-replace function and related tests

### PR DESCRIPTION
**Pull request by jtamagnan**
@magnars this feature never existed and I didn't know if it was because there was some opposition to it in the past or if it never felt necessary because of `mc/insert-numbers` but issue #237 mentions something of this nature and I thought to implement it. The variable that changes is `mc/id`. I also added the necessary tests

### CODE REVIEW

**Comment by magnars** [comment]
I would just use `mc/insert-numbers` and a regular eval-and-replace. Those are more composable primitives, but with the trade-off that it's not as discoverable. Maybe what we need is a more fleshed out tutorial/tips with examples of usage for this case and others? What do you think?

**Comment by jtamagnan** [comment]
Would you want to use github's wiki feature? There could be a section called recipes with more in depth bits of code and examples than the tips and tricks section?

**Comment by jtamagnan** [comment]
Maybe this snippet of code could go in that recipes section in case that some users like @ddovod would still like this feature. Perhaps even a recommendation to bind it to `C-x C-e` in the `mc/keymap`

**Comment by magnars** [comment]
> Would you want to use github's wiki feature? 

Quite possibly, if we have enough tips to fill it up. :)

> Maybe this snippet of code could go in that recipes section in case that some users like @ddovod would still like this feature.

I still think we should show people how to compose the primitives, instead of coding up special cases.

**Comment by purcell** [comment]
I'd also vote in favour of less shipped code and more examples which promote understanding. :-)

**Comment by jtamagnan** [comment]
Would we want to include gifs. Maybe for this example we would want something similar to:
output
Maybe less fast?

**Comment by magnars** [comment]
That looks great! I think the speed could be a little slower, like you
said. Thumbs up!
tir. 3. mai 2016 kl. 00.33 skrev Jules Tamangan <notifications@github.com>:

**Comment by jtamagnan** [comment]
I've fixed up the previous gif to make it a bit slower and be better compressed without the jpeg artifacts.

slow_squares

If we were to get a list of possible examples we could then create a more full example wiki page

**Comment by magnars** [comment]
Nicely done!

I guess one other demonstration that's worthwhile is to show off
`mc/mark-all-dwim`, which is basically all I use.

**Pull request closed without merging**
