### PR TITLE
Add mc/insert-letters function and test cases

### PR DESCRIPTION
**Pull request by jtamagnan**
* README.md: Add to readme, under special section.
 * features/insert-letters.feature: Add scenarios.
 * features/step-definitions/multiple-cursors-steps.el: Add call.
 * features/support/env.el: Add keybinding for insert-letters to H-3.
 * mc-separate-operations.el: Add function and helper functions.
 * multiple-cursors-core.el: Add insert-letters to functions that run once.
 * multiple-cursors.el: Add to readme.

### CODE REVIEW

**Comment by jtamagnan** [comment]
This was inspired by #186

**Comment by jtamagnan** [comment]
What do you think of as an addition for the feature request in #186 @magnars?

**Comment by magnars** [comment]
Looks good! Thank you. :)

**Comment by Fuco1** [comment]
Awesome, thanks for fixing my request!

**Pull request merged**
